### PR TITLE
Melee attack

### PR DESCRIPTION
**Pull request by alexisbader**
## ClickUp ticket link

[Game - Melee Attack](https://app.clickup.com/t/860qxryv3)

## Implementation description
Wrote script for melee attack logic in the enemy class (inherited from character) 
I created another controller for the bandit animation. I found that we didn't need both the left and right side animation (I kept the other one in for now). 

## Steps to test
1. Play the game and move the character around. When the enemy comes into contact with the player the console will print PLAYER HIT and the attack animation should be triggered (it is a bit delayed atm, im thinking we may need to freeze the character for a moment once it attacks) 

## Checklist
- [ ] My PR name is descriptive
- [ ] My commit messages are descriptive. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [ ] My code is organized, and commented and documented so that another dev can understand what I did

### CODE REVIEW

**Comment by 682x** [comment]
Right now, the attack cooldown function isn't called after performing an attack, so several attacks are actually performed. You can see that the PLAYER HIT message gets displayed several times per hit. This could be the cause of the animation delay.

Some other small things:
- In PerformAttack(), the call to IsPlayerInAttackRange() at the start isn't needed and may cause some delay
- I think it makes more sense if the attack animation plays even if the attack doesn't hit the player

**Comment by IsaacYu15** [comment]
In terms of the collision system, I was wondering why we built our own collision system rather than using Unity's (i.e. the rigid body and box collider should handle all the collisions already).

**Comment by 682x** [comment]
All the movement is kinematic (controlled by scripts), so the standard collision system detects collisions, but does not handle them

**Comment by alexisbader** [comment]
@682x Thanks for the suggestions! I implemented them and fixed the bug, should all be working now except for the animation delay which I opened a different ticket for.

**Comment by 682x** [comment]
Made some minor changes so that the demo works more consistently. Looks good to merge.

**Comment by alexisbader** [comment]
@682x Did you mean to close the pr? I can reopen and merge if all is good.

**Comment by 682x** [comment]
My bad, I clicked the wrong the button when I commented

**Review by 682x — APPROVED** [review]

**Pull request merged**
