### PR TITLE
Create Character and Player class, implement basic movement

### PR DESCRIPTION
**Pull request by 682x**
## ClickUp ticket link

[Game - Character Movement](https://app.clickup.com/t/860q9n1xn)

## Implementation description
- Added Character parent class and Player child class
- Implemented left/right movement, jumping, and falling
- Created framework for collisions, currently works with the ground but not platforms

## Steps to test
1. Open the MovementDemo scene
2. Press play and wait for the game to load
3. Press A to move left and D to move right
4. Press W to jump
5. Edit movement parameters as needed in the "Player" object sidebar menu

## What should reviewers focus on?
- Character class should be inherited for Enemy class
- Movement parameters can be changed as needed for different characters
- Add a Rigidbody collider to any new characters created

## Checklist
- [X] My PR name is descriptive
- [X] My commit messages are descriptive. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [X] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [X] My code is organized, and commented and documented so that another dev can understand what I did

### CODE REVIEW

**Comment by alexisbader** [comment]
I can't seem to get any movement from the keyboard input, is there anything I need to set up? 

Also, are you getting this error: 
Physics.ClosestPoint can only be used with a BoxCollider, SphereCollider, CapsuleCollider and a convex MeshCollider.
UnityEngine.Collider:ClosestPoint (UnityEngine.Vector3)
Character:OnTriggerEnter (UnityEngine.Collider) (at Assets/Character.cs:69)

It goes away if I check the convex box on the ground object but I don't really know what the implications of that are.

**Comment by 682x** [comment]
I use Unity's default input for movement control. You can check in Edit -> Project Settings to see what the keys are mapped to in your editor. Let me know if it still doesn't work if the keys are set up correctly.

For the convex error, I changed the Ground object to a box instead of a mesh to resolve that issue. I'll take a look as to why that change wasn't committed.

**Comment by alexisbader** [comment]
It is mapped correctly, I still can't get any movement :(

**Review by alexisbader — APPROVED** [review]
it all works for me now. looks good

**Pull request merged**
